Include TEST_DEPENDS
There are many cycles among test dependencies but that is acceptable in
combination with package seeding.

Signed-off-by: Tobias Kortkamp <t@tobik.me>

diff --git a/ports-mgmt/poudriere-devel/files/patch-package-seeding b/ports-mgmt/poudriere-devel/files/patch-package-seeding
--- a/ports-mgmt/poudriere-devel/files/patch-package-seeding
+++ b/ports-mgmt/poudriere-devel/files/patch-package-seeding
@@ -87,7 +87,46 @@ https://github.com/freebsd/poudriere/pull/554
  		else
  			# Only set PKGENV during 'package' to prevent
  			# testport-built packages from going into the main repo
-@@ -7320,6 +7326,10 @@ prepare_ports() {
+@@ -4454,6 +4460,7 @@ deps_fetch_vars() {
+ 		[ -n "${_origin_flavor}" ] && \
+ 		    err 1 "deps_fetch_vars: Using DEPENDS_ARGS but attempted lookup on ${originspec}"
+ 	fi
++	if [ "${PKG_SEEDING}" != "no" ]; then
+ 	if ! port_var_fetch_originspec "${originspec}" \
+ 	    PKGNAME _pkgname \
+ 	    ${_depends_args} \
+@@ -4463,13 +4470,29 @@ deps_fetch_vars() {
+ 	    IGNORE _ignore \
+ 	    ${_changed_deps} \
+ 	    ${_changed_options} \
++	    _PDEPS='${PKG_DEPENDS} ${EXTRACT_DEPENDS} ${PATCH_DEPENDS} ${FETCH_DEPENDS} ${BUILD_DEPENDS} ${LIB_DEPENDS} ${RUN_DEPENDS} ${TEST_DEPENDS}' \
++	    '${_PDEPS:C,([^:]*):([^:]*):?.*,\2,:C,^${PORTSDIR}/,,:O:u}' \
++	    _pkg_deps; then
++		msg_error "Error looking up dependencies for ${COLOR_PORT}${originspec}${COLOR_RESET}"
++		return 1
++	fi
++	else
++	if ! port_var_fetch_originspec "${originspec}" \
++	    PKGNAME _pkgname \
++	    ${_depends_args} \
++	    ${_lookup_flavors} \
++	    '${_DEPEND_SPECIALS:C,^${PORTSDIR}/,,}' _depend_specials \
++	    CATEGORIES categories \
++	    IGNORE _ignore \
++	    ${_changed_deps} \
++	    ${_changed_options} \
+ 	    _PDEPS='${PKG_DEPENDS} ${EXTRACT_DEPENDS} ${PATCH_DEPENDS} ${FETCH_DEPENDS} ${BUILD_DEPENDS} ${LIB_DEPENDS} ${RUN_DEPENDS}' \
+ 	    '${_PDEPS:C,([^:]*):([^:]*):?.*,\2,:C,^${PORTSDIR}/,,:O:u}' \
+ 	    _pkg_deps; then
+ 		msg_error "Error looking up dependencies for ${COLOR_PORT}${originspec}${COLOR_RESET}"
+ 		return 1
+ 	fi
+-
++	fi
+ 	[ -n "${_pkgname}" ] || \
+ 	    err 1 "deps_fetch_vars: failed to get PKGNAME for ${originspec}"
+ 
+@@ -7320,6 +7343,10 @@ prepare_ports() {
  
  	clean_build_queue
  
@@ -98,7 +137,7 @@ https://github.com/freebsd/poudriere/pull/554
  	# Call the deadlock code as non-fatal which will check for cycles
  	msg "Sanity checking build queue"
  	bset status "pkgqueue_sanity_check:"
-@@ -7446,6 +7456,67 @@ load_priorities() {
+@@ -7446,6 +7473,67 @@ load_priorities() {
  	return 0
  }
  
@@ -166,7 +205,7 @@ https://github.com/freebsd/poudriere/pull/554
  balance_pool() {
  	[ "${PWD}" = "${MASTERMNT}/.p" ] || \
  	    err 1 "balance_pool requires PWD=${MASTERMNT}/.p"
-@@ -7971,6 +8042,8 @@ DRY_RUN=0
+@@ -7971,6 +8059,8 @@ DRY_RUN=0
  : ${BUILDNAME:=$(date +${BUILDNAME_FORMAT})}
  
  : ${HTML_TYPE:=inline}
