Use pkg fetch and get some package verification for free
Signed-off-by: Tobias Kortkamp <t@tobik.me>

diff --git a/ports-mgmt/poudriere-devel/files/patch-package-seeding b/ports-mgmt/poudriere-devel/files/patch-package-seeding
--- a/ports-mgmt/poudriere-devel/files/patch-package-seeding
+++ b/ports-mgmt/poudriere-devel/files/patch-package-seeding
@@ -1,19 +1,7 @@
 Based on
 https://github.com/freebsd/poudriere/pull/554
 
---- src/etc/poudriere.conf.sample.orig	2019-02-12 19:20:15 UTC
-+++ src/etc/poudriere.conf.sample
-@@ -311,3 +311,9 @@ DISTFILES_CACHE=/usr/ports/distfiles
- # processing of the queue slightly, especially for bulk -a builds.
- # Default: no
- #HTML_TRACK_REMAINING=yes
-+
-+# Do package seeding or not (fetching required binary packages from a mirror
-+# that has the exact version we want)
-+# Default: no
-+#PKG_SEEDING=yes
-+#PKG_SEEDING_MIRROR=pkg.freebsd.org
---- src/share/poudriere/bulk.sh.orig	2019-02-12 19:20:15 UTC
+--- src/share/poudriere/bulk.sh.orig	2019-03-01 00:50:44 UTC
 +++ src/share/poudriere/bulk.sh
 @@ -58,6 +58,7 @@ Options:
      -p tree     -- Specify on which ports tree the bulk build will be done
@@ -42,9 +30,9 @@ https://github.com/freebsd/poudriere/pull/554
  			;;
  		S)
  			SKIP_RECURSIVE_REBUILD=1
---- src/share/poudriere/common.sh.orig	2019-02-12 19:20:15 UTC
+--- src/share/poudriere/common.sh.orig	2019-03-01 00:50:44 UTC
 +++ src/share/poudriere/common.sh
-@@ -1640,7 +1640,7 @@ enter_interactive() {
+@@ -1646,7 +1646,7 @@ enter_interactive() {
  		ensure_pkg_installed force_extract || \
  		    err 1 "Unable to extract pkg."
  		# Install the selected pkg package
@@ -53,7 +41,7 @@ https://github.com/freebsd/poudriere/pull/554
  		    /usr/bin/make -C \
  		    ${PORTSDIR}/$(injail /usr/bin/make \
  		    -f ${PORTSDIR}/Mk/bsd.port.mk -V PKGNG_ORIGIN) \
-@@ -1658,14 +1658,14 @@ enter_interactive() {
+@@ -1664,14 +1664,14 @@ enter_interactive() {
  		originspec_decode "${originspec}" port dep_args flavor
  		# Install run-depends since this is an interactive test
  		msg "Installing run-depends for ${COLOR_PORT}${port} | ${pkgname}"
@@ -70,7 +58,7 @@ https://github.com/freebsd/poudriere/pull/554
  		    /usr/bin/make -C ${PORTSDIR}/${port} ${dep_args} \
  		    ${flavor:+FLAVOR=${flavor}} install-package ||
  		    msg_warn "Failed to install ${COLOR_PORT}${port} | ${pkgname}"
-@@ -3162,7 +3162,7 @@ _real_build_port() {
+@@ -3167,7 +3167,7 @@ _real_build_port() {
  
  		if [ "${phase#*-}" = "depends" ]; then
  			# No need for nohang or PORT_FLAGS for *-depends
@@ -79,7 +67,7 @@ https://github.com/freebsd/poudriere/pull/554
  			    /usr/bin/make -C ${portdir} ${MAKE_ARGS} \
  			    ${phase} || return 1
  		else
-@@ -7145,6 +7145,10 @@ prepare_ports() {
+@@ -7170,6 +7170,10 @@ prepare_ports() {
  
  	clean_build_queue
  
@@ -90,7 +78,7 @@ https://github.com/freebsd/poudriere/pull/554
  	# Call the deadlock code as non-fatal which will check for cycles
  	msg "Sanity checking build queue"
  	bset status "pkgqueue_sanity_check:"
-@@ -7264,6 +7268,72 @@ load_priorities() {
+@@ -7289,6 +7293,48 @@ load_priorities() {
  	return 0
  }
  
@@ -100,8 +88,7 @@ https://github.com/freebsd/poudriere/pull/554
 +	[ "${PWD}" = "${MASTERMNT}/.p" ] || \
 +	    err 1 "pkg_seeding requires PWD=${MASTERMNT}/.p"
 +
-+	local url url_prefix jail_version jail_arch dest
-+	local seed_total seed_ok
++	local abi fetched_pkg jail_version jail_arch pkg_cmd pkgs
 +
 +	# Set up URL prefix
 +	jail_version=$(jget ${JAILNAME} version)
@@ -109,68 +96,43 @@ https://github.com/freebsd/poudriere/pull/554
 +	jail_version="${jail_version%%.*}"
 +	jail_arch=$(jget ${JAILNAME} arch)
 +	jail_arch=$(echo ${jail_arch} | sed 's,^arm64\.,,' | sed 's,^arm\.,,')
-+	url_prefix="${PKG_SEEDING_METHOD}://${PKG_SEEDING_MIRROR}"
-+	url_prefix="${url_prefix}/FreeBSD:${jail_version}:${jail_arch}/latest/All"
 +
-+	msg "Seeding packages from ${PKG_SEEDING_MIRROR}"
++	msg "Seeding packages"
 +	bset status "packageseeding:"
 +
-+	seed_ok=0
-+	parallel_start
++	abi="FreeBSD:${jail_version}:${jail_arch}"
++	pkgs=
++	fetched_pkg=
 +	while read pkgname originspec dep_reason; do
-+		# Don't fetch ports explicitly requested to be built
-+		# Only fetch dependencies the users don't bother being built
-+		# by others
-+		pkgname="${pkgname}.${PKG_EXT}"
-+		url="${url_prefix}/${pkgname}"
-+		dest="${PACKAGES}/All/${pkgname}"
-+		mkdir -p "${PACKAGES}/All"
-+		if [ "${dep_reason}" != "listed" ] && [ ! -f "$dest" ]; then
-+			parallel_run pkg_seeding_download "${url}" "${pkgname}" "${originspec}" && \
-+                seed_ok=$((${seed_ok} + 1))
++		# Don't fetch packages explicitly requested to be built
++		if [ "${dep_reason}" != "listed" ]; then
++			pkgs="${pkgs} ${pkgname}"
++		fi
++		if [ "${originspec}" = "ports-mgmt/pkg" ] || [ "${originspec}" = "ports-mgmt/pkg-devel" ]; then
++			fetched_pkg="${pkgname}"
 +		fi
 +	done < "all_pkgs"
 +
-+	if ! parallel_stop; then
-+		#err 1 "Fatal errors encountered seeding packages."
++	pkg_cmd="/usr/local/sbin/pkg -o ABI=${abi} -o PKG_DBDIR=/var/db/poudriere/pkg/${abi}"
++	if ! ${pkg_cmd} fetch -r FreeBSD -y -o "${PACKAGES}" ${pkgs}; then
++		err 1 "pkg fetch failed"
 +	fi
-+
-+	msg "Package seeding done, seeded ${seed_ok} packages."
-+}
-+
-+pkg_seeding_download() {
-+	[ $# -ne 3 ] && eargs pkg_seeding_download url pkgname originspec
-+
-+	msg_debug "Seeding package from: $1"
-+	(
-+		cd "${PACKAGES}/All"
-+		fetch -a -w 1 -m -o "$2" "$1" || fetch -a -w 1 -r -o "$2" "$1"
-+	)
-+
-+	if [ $? -eq 0 ]; then
-+		msg_verbose "Successfully seeded $3 to $2"
-+		if [ "$3" = "ports-mgmt/pkg" ] || [ "$3" = "ports-mgmt/pkg-devel" ]; then
-+			mkdir -p "${PACKAGES}/Latest"
-+			install -l rs "${PACKAGES}/All/${2}" "${PACKAGES}/Latest/pkg.txz"
-+		fi
-+		return 0
-+	else
-+		msg_debug "Failed seeding $3"
-+		return 1
++	if [ -n "${fetched_pkg}" ]; then
++		mkdir -p "${PACKAGES}/Latest"
++		install -l rs "${PACKAGES}/All/${fetched_pkg}.${PKG_EXT}" "${PACKAGES}/Latest/pkg.${PKG_EXT}"
 +	fi
++	msg "Package seeding done"
 +}
 +
  balance_pool() {
  	[ "${PWD}" = "${MASTERMNT}/.p" ] || \
  	    err 1 "balance_pool requires PWD=${MASTERMNT}/.p"
-@@ -7786,6 +7856,10 @@ DRY_RUN=0
+@@ -7812,6 +7858,8 @@ DRY_RUN=0
  : ${BUILDNAME:=$(date +${BUILDNAME_FORMAT})}
  
  : ${HTML_TYPE:=inline}
 +
 +: ${PKG_SEEDING:=no}
-+: ${PKG_SEEDING_METHOD:=https}
-+: ${PKG_SEEDING_MIRROR:=pkg.freebsd.org}
  
  if [ -n "${MAX_MEMORY}" ]; then
  	MAX_MEMORY_BYTES="$((${MAX_MEMORY} * 1024 * 1024 * 1024))"
