Retry pkg fetch several times
Signed-off-by: Tobias Kortkamp <t@tobik.me>

diff --git a/ports-mgmt/poudriere-devel/files/patch-package-seeding b/ports-mgmt/poudriere-devel/files/patch-package-seeding
--- a/ports-mgmt/poudriere-devel/files/patch-package-seeding
+++ b/ports-mgmt/poudriere-devel/files/patch-package-seeding
@@ -1,7 +1,7 @@
 Based on
 https://github.com/freebsd/poudriere/pull/554
 
---- src/share/poudriere/bulk.sh.orig	2019-03-01 00:50:44 UTC
+--- src/share/poudriere/bulk.sh.orig	2019-03-11 16:30:03 UTC
 +++ src/share/poudriere/bulk.sh
 @@ -58,6 +58,7 @@ Options:
      -p tree     -- Specify on which ports tree the bulk build will be done
@@ -30,9 +30,9 @@ https://github.com/freebsd/poudriere/pull/554
  			;;
  		S)
  			SKIP_RECURSIVE_REBUILD=1
---- src/share/poudriere/common.sh.orig	2019-03-01 00:50:44 UTC
+--- src/share/poudriere/common.sh.orig	2019-03-11 16:30:03 UTC
 +++ src/share/poudriere/common.sh
-@@ -1646,7 +1646,7 @@ enter_interactive() {
+@@ -1645,7 +1645,7 @@ enter_interactive() {
  		ensure_pkg_installed force_extract || \
  		    err 1 "Unable to extract pkg."
  		# Install the selected pkg package
@@ -41,7 +41,7 @@ https://github.com/freebsd/poudriere/pull/554
  		    /usr/bin/make -C \
  		    ${PORTSDIR}/$(injail /usr/bin/make \
  		    -f ${PORTSDIR}/Mk/bsd.port.mk -V PKGNG_ORIGIN) \
-@@ -1664,14 +1664,14 @@ enter_interactive() {
+@@ -1663,14 +1663,14 @@ enter_interactive() {
  		originspec_decode "${originspec}" port dep_args flavor
  		# Install run-depends since this is an interactive test
  		msg "Installing run-depends for ${COLOR_PORT}${port} | ${pkgname}"
@@ -58,7 +58,7 @@ https://github.com/freebsd/poudriere/pull/554
  		    /usr/bin/make -C ${PORTSDIR}/${port} ${dep_args} \
  		    ${flavor:+FLAVOR=${flavor}} install-package ||
  		    msg_warn "Failed to install ${COLOR_PORT}${port} | ${pkgname}"
-@@ -3167,7 +3167,7 @@ _real_build_port() {
+@@ -3201,7 +3201,7 @@ build_port() {
  
  		if [ "${phase#*-}" = "depends" ]; then
  			# No need for nohang or PORT_FLAGS for *-depends
@@ -67,7 +67,7 @@ https://github.com/freebsd/poudriere/pull/554
  			    /usr/bin/make -C ${portdir} ${MAKE_ARGS} \
  			    ${phase} || return 1
  		else
-@@ -7170,6 +7170,10 @@ prepare_ports() {
+@@ -7178,6 +7178,10 @@ prepare_ports() {
  
  	clean_build_queue
  
@@ -78,7 +78,7 @@ https://github.com/freebsd/poudriere/pull/554
  	# Call the deadlock code as non-fatal which will check for cycles
  	msg "Sanity checking build queue"
  	bset status "pkgqueue_sanity_check:"
-@@ -7289,6 +7293,61 @@ load_priorities() {
+@@ -7298,6 +7302,67 @@ load_priorities() {
  	return 0
  }
  
@@ -88,7 +88,7 @@ https://github.com/freebsd/poudriere/pull/554
 +	[ "${PWD}" = "${MASTERMNT}/.p" ] || \
 +	    err 1 "pkg_seeding requires PWD=${MASTERMNT}/.p"
 +
-+	local abi dbdir fetched_pkg jail_version jail_arch pkg_cmd pkgs repo
++	local abi dbdir fetched_pkg i jail_version jail_arch pkg_cmd pkgs repo
 +
 +	# Set up URL prefix
 +	jail_version=$(jget ${JAILNAME} version)
@@ -127,9 +127,15 @@ https://github.com/freebsd/poudriere/pull/554
 +		# The FreeBSD repository might be disabled on the build host...
 +		echo 'FreeBSD: { enabled: yes }' > "${dbdir}/repos/FreeBSD.conf"
 +	fi
-+	if ! ${pkg_cmd} fetch -r "${repo}" -y -o "${PACKAGES}" ${pkgs}; then
-+		err 1 "pkg fetch failed"
-+	fi
++	# Sometimes pkg fetch fails to fetch packages with the correct checksum
++	# on the first try.  Retry several times to work around this bug(?).
++	i=0
++	while ! ${pkg_cmd} fetch -r "${repo}" -y -o "${PACKAGES}" ${pkgs}; do
++		i=$((i + 1))
++		if [ $i -ge 20 ]; then
++			err 1 "pkg fetch failed"
++		fi
++	done
 +	if [ -n "${fetched_pkg}" ]; then
 +		mkdir -p "${PACKAGES}/Latest"
 +		install -l rs "${PACKAGES}/All/${fetched_pkg}.${PKG_EXT}" "${PACKAGES}/Latest/pkg.${PKG_EXT}"
@@ -140,7 +146,7 @@ https://github.com/freebsd/poudriere/pull/554
  balance_pool() {
  	[ "${PWD}" = "${MASTERMNT}/.p" ] || \
  	    err 1 "balance_pool requires PWD=${MASTERMNT}/.p"
-@@ -7812,6 +7871,8 @@ DRY_RUN=0
+@@ -7821,6 +7886,8 @@ DRY_RUN=0
  : ${BUILDNAME:=$(date +${BUILDNAME_FORMAT})}
  
  : ${HTML_TYPE:=inline}
